[server]
port = 8501
enableCORS = false
runOnSave = true
fileWatcherType = "watchdog"

[theme]
primaryColor = "#059669"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0fdf4"
textColor = "#1f2937"
font = "sans serif"

[browser]
gatherUsageStats = false