[server]
port = 8501
enableCORS = false
runOnSave = true
fileWatcherType = "watchdog"
folderWatchExclusions = ["**/.git", "**/venv", "**/__pycache__", "**/node_modules", "*.pyc", ".env"]

[theme]
primaryColor = "#059669"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0fdf4"
textColor = "#1f2937"
font = "sans serif"

[browser]
gatherUsageStats = false